# Reference: https://github.com/niketagrawal/sphinx-gh-pages/blob/main/.github/workflows/sphinx.yml

name: sphinx-docs-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on (starts ubuntu vm)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
            python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Example of using a custom build-command.
      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: Build PDF
        run: |
          cd docs/
          make simplepdf

      # Imports generated html into GitHub Pages
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/build/html
